# fly.toml app configuration file generated for wmg-frontend on 2023-10-28T01:20:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wmg-frontend"
primary_region = "ams"

[build]

[env]
  REACT_APP_BACKEND_URL = "wmg-backend.internal"
  ENV = "PROD"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          Access-Control-Allow-Headers = "*"
          Access-Control-Allow-Methods = "*"
          Access-Control-Allow-Origin = "*"
