# fly.toml app configuration file generated for wmg-frontend on 2023-10-26T21:19:38+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wmg-frontend"
primary_region = "ams"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # https://community.fly.io/t/edge-headers/9278
  [services.ports.http_options.response.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

[env]
  REACT_APP_BACKEND_URL = "wmg-backend.internal"
