services:
  frontend:
    image: wmg-front
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        - ENV=DEV
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_BACKEND_URL=http://backend.world-music-geek-web.orb.local
  
  backend:
    image: wmg-back
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
