# fly.toml app configuration file generated for wmg-backend on 2023-10-26T21:16:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wmg-backend"
primary_region = "ams"

[build]


[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
