# Generated by Django 4.0.5 on 2022-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.TextField(blank=True)),
                ('post_create', models.DateTimeField()),
                ('post_edit', models.DateTimeField(auto_now=True)),
                ('post_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('post_is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
